services:
  - type: web
    name: autovalor-ec
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app -w 2 -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
